### ISSUE TITLE
nullable fields

### ISSUE THREAD

**Issue by ribrdb** [FirebaseExtended/protobuf-rules-gen#24]
Our javascript code is setting optional fields to null instead of deleting them.
This fails the type checks this project generates.

**Comment by ribrdb** [comment]
After thinking about this some more, it seems like this could be an important case to support.
For example if I want to query for all Books that have no Author. I can query for 'Author == null', but not for 'Author property does not exist'.

**Comment by rockwotj** [comment]
It is an important use case, and I want to add it.

What do you think is the best way to enable this? Per field? That could be a bit verbose:

```
message Book {
  string author = 1 [(google.firebase.rules.firebase_rules_field).nullable = true];
}
```

or maybe:

```
message Book {
   [(google.firebase.rules.firebase_rules_message).nullable_fields = true]; // For all fields
  string author = 1;
}
```

**Comment by ribrdb** [comment]
Those both look good. Any reason to not support both?

**Comment by rockwotj** [comment]
This is implemented however, since it's been moved to a new org, I don't have permissions to push anymore, once I get this resolved I'll open a PR.
