### ISSUE TITLE
Request for v0.2.2

### ISSUE THREAD

**Issue by kevlened** [FirebaseExtended/protobuf-rules-gen#31]
This library makes it so much easier to safely expose firestore to public clients, thanks!

I'm trying to use the new `nullable` firebase_rules_field option and I ran into the issue fixed here: https://github.com/FirebaseExtended/protobuf-rules-gen/commit/99af1c30d123a5aa575342ca20878f2f854639b9. I pull the latest binary from Releases so my team doesn't have to rebuild it. Do you mind publishing a patch version?

**Comment by samtstern** [comment]
@rockwotj can you release a patch version?  I'd do it but I am not familiar with the release proocess.

**Comment by rockwotj** [comment]
Yes will do soon, sorry for some reason I don't get these reports alerts anymore.

**Comment by rockwotj** [comment]
I created a release and added a macos binary:
* https://github.com/FirebaseExtended/protobuf-rules-gen/releases/tag/v0.2.2

I'll get a linux binary up Monday.

**Comment by rockwotj** [comment]
Also @samtstern there are release instructions at the bottom of the README :)

The online thing here is you have to build a binary for each platform. Well except windows because I don't have access to a windows box and setting up bazel for windows is a nightmare

**Comment by kevlened** [comment]
Thanks @rockwotj  and @samtstern!
