### ISSUE TITLE
Can't setup protoc-gen-firebase_rules (Missing input file)

### ISSUE THREAD

**Issue by AndroidNils** [FirebaseExtended/protobuf-rules-gen#38]
I try to set up this library. Unfortunately I have problems with [step no. 3](https://github.com/FirebaseExtended/protobuf-rules-gen#usage):

> 3. Either put the plugin binary on your $PATH or use the --plugin=protoc-gen-firebase_rules=./path/to/protoc-gen-firebase_rules option

If I do this, I get this **error message**: `Missing input file`.

What I tried:
* `protoc --plugin=protoc-gen-firebase_rules`
* `protoc --plugin=protoc-gen-firebase_rules=/Users/nils/Desktop/SDKs/protoc-gen-firebase_rules`
* `protoc --plugin=protoc-gen-firebase_rules=./protoc-gen-firebase_rules`
* `protoc --plugin=protoc-gen-firebase_rules=protoc-gen-firebase_rules`

Additional information:
* I already added `protoc-gen-firebase_rules` to my `$PATH` (`export PATH=/Users/nils/Desktop/SDKs:$PATH`)
* protoc --version: `libprotoc 3.13.0`
* MacOS: `10.15.5`

**Comment by samtstern** [comment]
@AndroidNils you're missing one more argument: the proto files you want to compile.

I did this and got your error:
```
$ protoc --plugin=~/Downloads/protoc-gen-firebase_rules --firebase_rules_out=./gen
Missing input file.
```

And then I pointed to the `.proto` file and it worked:
```
$ protoc --plugin=$HOME/Downloads/protoc-gen-firebase_rules --firebase_rules_out=./gen rules.proto
```
