### ISSUE TITLE
How about the status of this project?

### ISSUE THREAD

**Issue by KimuraYu45z** [FirebaseExtended/protobuf-rules-gen#39]
I want to use this library with latest development environment.
Furthermore, I want to use in Ubuntu but the compiled binary is only for mac os x86 x64 but because of deprecated bazel configuratinos, I can't build from the source code.

So I want to hear about the status of this project.
Source codes written in C++ seems to work even now so plz update the bazel configurations. ( And migrate to protobuf3 completely)

**Comment by var-const** [comment]
Thank you for filing the issue. The repository is being maintained on a best-effort basis -- we prioritize other projects at the moment, but we are always open to reviewing contributions.

I have reproed this on a Linux machine and can confirm that Linux build is currently broken and Bazel configuration needs to be updated. If you're interested in working on a fix for this, we would gladly review it. Otherwise, I can take a look at this sometime later this month.

**Comment by KimuraYu45z** [comment]
Thank you very much. I'll wait for later this month.
In addition, I would appreciate if the binary for linux_amd64 is distributed because making a build environment with Bazel in Docker is bothersome.

Thanks.

**Comment by ryuseikurata** [comment]
Hope the release can happen.

**Comment by KimuraYu45z** [comment]
https://github.com/FirebaseExtended/protobuf-rules-gen/pull/43
This PR was merged. Thank you very much.

@var-const Could you create a "release"?

**Comment by var-const** [comment]
@KimuraYu45z I will work on a release tomorrow. Thank you again for the patch (#43).

**Comment by var-const** [comment]
@KimuraYu45z I have prepared release [v0.2.3](https://github.com/FirebaseExtended/protobuf-rules-gen/releases/tag/v0.2.3).

**Comment by KimuraYu45z** [comment]
@var-const Thank you! LGTM!
I think it is ok to be not "pre" release.

**Comment by var-const** [comment]
@KimuraYu45z The previous owner of the repo marked each release as "pre-release", probably to highlight that this is a "best effort" product. I'm just following his approach on this.

**Comment by KimuraYu45z** [comment]
@var-const Thanks, I see.

https://github.com/FirebaseExtended/protobuf-rules-gen/blob/master/.github/workflows/binary.yml#L6

I wrote the trigger of github actions workflow as `release` `created` but it will not be emitted when `pre-release` is created.

I need to change it to `release` `published` which will be emitted when also `pre-release`.

**Comment by var-const** [comment]
> I need to change it to `release` `published` which will be emitted when also `pre-release`.
Sounds good.

**Comment by KimuraYu45z** [comment]
@var-const https://github.com/FirebaseExtended/protobuf-rules-gen/pull/44/files
I made the PR. I would appreciate if you review it. Thanks

**Comment by var-const** [comment]
Merged, thanks!
